spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

ribbon:
  IsSecure: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
  profiles: pcf
  jpa:
    database: MYSQL

---

spring:
  profiles: pws
  jpa:
    database: POSTGRESQL
